### PR TITLE
Add Bioregistry prefixes

### LINKED ISSUE #22: Add Bioregistry prefix column
It's great you're curating a registry here! I saw it's linking out to miriam prefixes so I figured it would be good to include [Bioregistry](https://github.com/biopragmatics/bioregistry) ones as well. This way it would be easier to monitor any potentially novel contributions here and suck them back in to the Bioregistry

I can write a script that does this based on Miriam and Wikidata mappings to demonstrate.

Edit: while working on this, I noticed there were several invalid MIRIAM prefixes, which lead to #23

### PR DESCRIPTION
**Pull request by cthoyt**
Closes #22

- [x] Add Bioregistry column and populate
- [x] Add metadata for Bioregistry data column
- [x] Add testing infrastructure to make sure Bioregistry prefixes are correct

Not all rows were mappable to the bioregistry. For example, there's a row for "Other" which seems to imply the absence of standardized semantics. Another issue was the "OpenTargets" entry seems to actually be redundant of Ensembl Gene. Some of the other resources (a lot of plant things) were hard to figure out since they were missing important metadata. I'll try that on a second pass.

See also https://github.com/biopragmatics/bioregistry/pull/388, where I added some missing prefixes to the Bioregistry to support this mapping.

### CODE REVIEW

**Comment by cthoyt** [comment]
@egonw not sure what happened but this branch wasn't merged properly?

**Comment by egonw** [comment]
What did you see that you reach that conclusion?

**Comment by cthoyt** [comment]
weird since I do see the commits on the main branch

Screen Shot 2022-05-21 at 18 47 57

**Comment by egonw** [comment]
Oh... I rebased this branch. That probably confused GitHub.

**Comment by cthoyt** [comment]
Would highly suggest using squash + merge to keep commit histories focused on high-level changes, then the PR is linked automatically and keeps the commit history on GitHub

**Comment by egonw** [comment]
I have very bad experiences with repeated merges back and forth between PRs and the main branch. Thanks for your recommendation, but not heading down that rabbit hole again.

**Pull request closed without merging**
