### PR TITLE
Add data integrity tests for MIRIAM URIs/URNs

### PR DESCRIPTION
**Pull request by cthoyt**
I found that there were several URNs pointing to prefixes in MIRIAM that do not exist. This pull request adds unit tests that check that all entries in the `uri` column starting with `urn:miriam`: are indeed valid MIRIAM prefixes.

Entries for the following were updated to use the correct MIRIAM prefixes:

- [x] FlyBase
- [x] MGI
- [x] OMIM
- [x] Pathway Ontology
- [x] PATO
- [x] Systems Biology Ontology
- [x] WormBase

Entries for the following are not available in MIRIAM and were removed:

- [x] BIND (this resource doesn't exist anymore)
- [x] IPI (this resource doesn't exist anymore)
- [x] SPRINT
- [x] Unipathway (MIRIAM has unipathway.reaction and unipathway.compound, neither seem appropriate)

For SPRINT and Unipathway, there are alternative prefixes from the Bioregistry (https://bioregistry.io/sprint and https://bioregistry.io/upa). For BIND and IPI, we can add prefixes to the Bioregistry and mark them as "deprecated", if that helps.

### CODE REVIEW

**Comment by egonw** [comment]
ping @Finterly, you last year some issues with upper/lower case things in the `datasources.csv`, so please take notice of the changes in this patch. no action is needed otherwise whatsoever.

**Comment by cthoyt** [comment]
I'm not quite sure I understood your feedback @egonw, are there any changes needed for this PR? Or do you have to first consider the downstream impact of standardizing terminology here?

**Comment by DeniseSl22** [comment]
@egonw : any time to check this PR from @cthoyt ?

**Comment by egonw** [comment]
cc @Finterly

**Review by egonw — CHANGES_REQUESTED** [review]
It currently fails with:

```
Traceback:
/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_integrity.py:7: in <module>
    from bioregistry.external.miriam import get_miriam
.tox/py/lib/python3.10/site-packages/bioregistry/external/__init__.py:8: in <module>
    from .biolink import get_biolink
.tox/py/lib/python3.10/site-packages/bioregistry/external/biolink.py:7: in <module>
    import yaml
E   ModuleNotFoundError: No module named 'yaml'
```

**Comment by egonw** [comment]
@cthoyt:

```
E   ModuleNotFoundError: No module named 'bs4'
```

**Comment by cthoyt** [comment]
getting there!

**Comment by egonw** [comment]
ping @cthoyt, there was overlap with the other PR. I pulled in one patch from this PR.

Can you have a look? And salvage other bits? For the changes in the `datasources.tsv`, please put this in an isolated PR because I want @Finterly to have a look at that, because of PathVisio depending on that info.

**Comment by cthoyt** [comment]
@egonw not sure if makes sense to put the PR for tests that are going to fail - the idea would be that once you implement some tests, you update the data to follow that standard and never let the tests fail again. But if that's what you can, I could separate these.

**Comment by egonw** [comment]
@Finterly, @mkutmon, please take note of the changes in upper/lower casing in the `datasources.tsv`. Fin, if I remember correctly, there was something about upper/lower case last year, but I cannot quite remember what it was. Are these changes going to cause any downstream issues?

**Comment by cthoyt** [comment]
@Finterly @mkutmon feedback would be appreciated

**Review by egonw — APPROVED** [review]

**Comment by egonw** [comment]
Okay, there are merge conflicts, so will have to do this one manually.

**Comment by cthoyt** [comment]
@egonw not sure what the issue is, in the most recent commit on this branch [289e54b](https://github.com/bridgedb/datasources/pull/23/commits/289e54b4250cf08fa98c2b5cf0a4e18db206a020) I addressed all conflicts with the main branch

**Comment by egonw** [comment]
> This branch cannot be rebased due to conflicts

It says "This branch cannot be rebased due to conflicts" ... i will explore, but after the meeting I am in.

**Comment by cthoyt** [comment]
Are you looking at the github interface for merging or trying to do this locally?

**Comment by egonw** [comment]
github interface

**Comment by cthoyt** [comment]
then I'd suggest doing "Squash and merge" which would turn all commits into this branch into a single one as it's merged. There isn't really any valuable information in the small commits made during this PR

**Pull request merged**
